### ISSUE TITLE
Please Namespace the class to a Module e.g. MTC.Crypto 

### ISSUE THREAD

**Issue by sworteu** [ktekinay/M_Crypto#3]
For readability and finding classes from MTC it would be good to have MTC.* as the base module.
This way everyone can simply add MTC classes to the MTC module and find them faster. Also in Xojo one can use:
`Using MTC`
Before the code to minify code rewriting.

**Comment by ktekinay** [comment]
Because my modules are various and diverse, and have been available for quite some time, I don't think this will make things easier. In fact, adding them to a project will get more complicated. I won't be doing this, but I appreciate the suggestion.
